name: Build

on: [pull_request]

jobs:
  build_qa:
    name: Build QA Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set the QA configuration file
      run: mv env-qa .env
    - name: Ensure we can build the image
      run: docker build -t test:test --target server .
